Factory/Models/Machines.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable
namespace Factory.Models
{
    public class Machine
    {
        public int MachineId { get; set; }

        [Required(ErrorMessage = "This field can't be left empty")]
        public string Name { get; set; } = "";

        public List<EngineerMachine> JoinEntities { get; } = new List<EngineerMachine>();
    }
#nullable disable
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;

namespace Factory.Controllers
{
	public class EngineersController : Controller
	{
		private readonly FactoryContext _db;

		public EngineersController(FactoryContext db)
		{
			_db = db;
		}

		public ActionResult Index()
		{
			List<Engineer> model = _db.Engineers.ToList();
			return View(model);
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Engineer Engineer)
		{
			_db.Engineers.Add(Engineer);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

public ActionResult Show(int id)
{
    Engineer thisEngineer = _db.Engineers
                            .Include(Engineer => Engineer.JoinEntities)
														.ThenInclude(join => join.Machine)
                            .FirstOrDefault(Engineer => Engineer.EngineerId == id);
    return View(thisEngineer);
}

public ActionResult AddMachine(int id)
{
	Engineer thisEngineer = _db.Engineers.FirstOrDefault(Engineers => Engineers.EngineerId == id);
	ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
	return View(thisEngineer);
}

[HttpPost] 
public ActionResult AddMachine(Engineer Engineer, int MachineId)
{
    #nullable enable
    EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == MachineId && join.EngineerId == Engineer.EngineerId));
    #nullable disable 
    if (joinEntity == null && MachineId != 0)
    {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = Engineer.EngineerId});
        _db.SaveChanges();
    }
    else
    {
        ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
        return View(Engineer);
    }
    return RedirectToAction("Show", new { id = Engineer.EngineerId });
}


public ActionResult Edit(int id)
{
	var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
	return View(thisEngineer);
}

[HttpPost]
public ActionResult Edit(int id, string name)
{
	var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
	thisEngineer.Name = name;
	_db.SaveChanges();
	return RedirectToAction("Index");
}

		public ActionResult Delete(int id)
		{
			Engineer thisEngineer = _db.Engineers.FirstOrDefault(Engineer => Engineer.EngineerId == id);
			return View(thisEngineer);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Engineer thisEngineer = _db.Engineers.FirstOrDefault(Engineer => Engineer.EngineerId == id);
			_db.Engineers.Remove(thisEngineer);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpPost]
		public ActionResult DeleteJoin(int joinId)
		{
			EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
			_db.EngineerMachines.Remove(joinEntry);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models; 
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

   [HttpPost]
public ActionResult Create(Machine Machine, int EngineerId)
{
    if (ModelState.IsValid)
    {
        _db.Machines.Add(Machine);
        _db.SaveChanges();

        if (EngineerId > 0)
        {
        }

        return RedirectToAction("Index");
    }
    else
    {
        ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
        return View(Machine);
    }
}


    public ActionResult Show(int id)
    {
      Machine thisMachine = _db.Machines
                              .Include(Machine => Machine.JoinEntities)
                              .ThenInclude(join => join.Engineer)
                              .FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(Machines => Machines.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine Machine, int EngineerId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == Machine.MachineId && join.EngineerId == EngineerId));
      #nullable disable
      if (joinEntity == null && EngineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = Machine.MachineId });
        _db.SaveChanges();
      }
      else
      {
        ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
        return View(Machine);
      }
      return RedirectToAction("Show", new { id = Machine.MachineId });
    }

public ActionResult Edit(int id)
{
	var thisMachine = _db. Machines.FirstOrDefault(machine => machine.MachineId == id);
	return View(thisMachine);
}

[HttpPost]
public ActionResult Edit(int id, string name)
{
	var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
	thisMachine.Name = name;
	_db.SaveChanges();
	return RedirectToAction("Index");
}

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a Engineer</h2>

<h4>Add a Engineer to this: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="save" />
}

Factory/Views/Machines/Create.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>
<div class="col">

    @using (Html.BeginForm())
    {
        @Html.LabelFor(model => model.Name, new { @class = "form-label"})
        @Html.TextBoxFor(model => model.Name,  new { @class = "form-control"})
        <br>
        
        <br><br>
        <input type="submit" value="Add new Machine" class="btn btn-primary btn-sm" />
    }
    <br>
<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;"}) </p>
<p>@Html.ActionLink("Show all Machines", "Index")</p>


</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
@using Factory.Models


<h4>Confirm Deletion?</h4>
<div class="col">

 @using (Html.BeginForm("Delete", "Machines", new { id = Model.MachineId }, FormMethod.Post))
{
  <input type="submit" value="Delete Machine" onclick="return confirm('Are you sure you want to delete this machine?')"/>
}

</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
@using Factory.Models

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

 @using (Html.BeginForm("Edit", "Machines", new { id = Model.MachineId }, FormMethod.Post))
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input class="btn" type ="submit" value="Edit" onclick="return confirm('Are you sure you want to edit this Machine?');"/>
}

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No Machines have been added yet!</h3>
} 

<ul>
  @foreach (Machine Machine in Model)
{
 <li>@Html.ActionLink($"{Machine.Name}", "Show", new { id = Machine.MachineId},null)</li>
}
</ul>


<p>@Html.ActionLink("Add a new Machine", "Create",null, new {})</p>

Factory/Views/Machines/Show.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
@using Factory.Models


@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine is not assigned to any engineers</p>
}
else
{
  <h4>This machine assigned to the following engineerss:</h4>
  <ul>
    @foreach(EngineerMachine join in Model.JoinEntities)
    {
      <li>Engineer: @join.Engineer.Name</li>
      @using (Html.BeginForm("DeleteJoin", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Engineer to Machine", "AddEngineer", new { id = Model.MachineId })</p>

@using (Html.BeginForm("Delete", "Engineers", new { id = Model.MachineId }, FormMethod.Post))
{
    <input type="submit" value="Delete Machine" onclick="location.href='@Url.Action("Delete", "Machines", new { id = Model.MachineId })'; return false;" />
  }

@using (Html.BeginForm("Edit", "Machines", new { id = Model.MachineId }, FormMethod.Post))
{
    <input type="submit" value="Edit Machine" onclick="location.href='@Url.Action("Edit", "Machines", new { id = Model.MachineId })'; return false;" />
  }